/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRouteRouteImport } from './routes/storage/route'
import { Route as CoreRouteRouteImport } from './routes/core/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AiRouteRouteImport } from './routes/ai/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as SchemaRouteRouteImport } from './routes/$schema/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorageIndexRouteImport } from './routes/storage/index'
import { Route as CoreIndexRouteImport } from './routes/core/index'
import { Route as AiIndexRouteImport } from './routes/ai/index'
import { Route as SchemaIndexRouteImport } from './routes/$schema/index'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthMfaRouteImport } from './routes/auth/mfa'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountRolesPermissionsRouteImport } from './routes/account/roles-permissions'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountIdentitiesRouteImport } from './routes/account/identities'
import { Route as StorageBucketIdRouteRouteImport } from './routes/storage/$bucketId/route'
import { Route as StorageBucketIdIndexRouteImport } from './routes/storage/$bucketId/index'
import { Route as CoreUsersIndexRouteImport } from './routes/core/users/index'
import { Route as CoreAudit_logsIndexRouteImport } from './routes/core/audit_logs/index'
import { Route as SchemaTemplateIndexRouteImport } from './routes/$schema/template/index'
import { Route as SchemaReportIndexRouteImport } from './routes/$schema/report/index'
import { Route as SchemaDashboardIndexRouteImport } from './routes/$schema/dashboard/index'
import { Route as SchemaChartIndexRouteImport } from './routes/$schema/chart/index'
import { Route as StorageBucketIdSplatRouteImport } from './routes/storage/$bucketId/$'
import { Route as CoreUsersNewRouteImport } from './routes/core/users/new'
import { Route as CoreUsersInviteRouteImport } from './routes/core/users/invite'
import { Route as CoreAudit_logsAuditLogIdRouteImport } from './routes/core/audit_logs/$auditLogId'
import { Route as CoreUsersUserIdRouteRouteImport } from './routes/core/users/$userId/route'
import { Route as SchemaResourceResourceRouteRouteImport } from './routes/$schema/resource/$resource/route'
import { Route as CoreUsersUserIdIndexRouteImport } from './routes/core/users/$userId/index'
import { Route as SchemaTemplateTemplateIndexRouteImport } from './routes/$schema/template/$template/index'
import { Route as SchemaResourceResourceIndexRouteImport } from './routes/$schema/resource/$resource/index'
import { Route as SchemaReportReportIndexRouteImport } from './routes/$schema/report/$report/index'
import { Route as CoreUsersUserIdSecurityRouteImport } from './routes/core/users/$userId/security'
import { Route as CoreUsersUserIdEditRouteImport } from './routes/core/users/$userId/edit'
import { Route as CoreUsersUserIdDangerRouteImport } from './routes/core/users/$userId/danger'
import { Route as SchemaResourceResourceTableRouteImport } from './routes/$schema/resource/$resource/table'
import { Route as SchemaResourceResourceSingleRouteImport } from './routes/$schema/resource/$resource/single'
import { Route as SchemaResourceResourceNewRouteImport } from './routes/$schema/resource/$resource/new'
import { Route as SchemaResourceResourceGridRouteImport } from './routes/$schema/resource/$resource/grid'
import { Route as SchemaResourceResourceDefinitionRouteImport } from './routes/$schema/resource/$resource/definition'
import { Route as SchemaResourceResourceTreeTreeIdRouteImport } from './routes/$schema/resource/$resource/tree/$treeId'
import { Route as SchemaResourceResourceTableSheetRouteImport } from './routes/$schema/resource/$resource/table.sheet'
import { Route as SchemaResourceResourceListListIdRouteImport } from './routes/$schema/resource/$resource/list/$listId'
import { Route as SchemaResourceResourceKanbanKanbanIdRouteImport } from './routes/$schema/resource/$resource/kanban/$kanbanId'
import { Route as SchemaResourceResourceGridSheetRouteImport } from './routes/$schema/resource/$resource/grid.sheet'
import { Route as SchemaResourceResourceGalleryGalleryIdRouteImport } from './routes/$schema/resource/$resource/gallery/$galleryId'
import { Route as SchemaResourceResourceCalendarCalendarIdRouteImport } from './routes/$schema/resource/$resource/calendar/$calendarId'
import { Route as SchemaResourceResourceResourceIdDetailRouteImport } from './routes/$schema/resource/$resource/$resourceId/detail'
import { Route as SchemaResourceResourceResourceIdCommentRouteImport } from './routes/$schema/resource/$resource/$resourceId/comment'
import { Route as SchemaResourceResourceResourceIdAuditRouteImport } from './routes/$schema/resource/$resource/$resourceId/audit'
import { Route as SchemaResourceResourceResourceIdDetailIndexRouteImport } from './routes/$schema/resource/$resource/$resourceId/detail.index'
import { Route as SchemaResourceResourceTreeTreeIdSheetRouteImport } from './routes/$schema/resource/$resource/tree/$treeId.sheet'
import { Route as SchemaResourceResourceListListIdSheetRouteImport } from './routes/$schema/resource/$resource/list/$listId.sheet'
import { Route as SchemaResourceResourceKanbanKanbanIdSheetRouteImport } from './routes/$schema/resource/$resource/kanban/$kanbanId.sheet'
import { Route as SchemaResourceResourceGalleryGalleryIdSheetRouteImport } from './routes/$schema/resource/$resource/gallery/$galleryId.sheet'
import { Route as SchemaResourceResourceCalendarCalendarIdSheetRouteImport } from './routes/$schema/resource/$resource/calendar/$calendarId.sheet'
import { Route as SchemaResourceResourceResourceIdDetailSheetRouteImport } from './routes/$schema/resource/$resource/$resourceId/detail.sheet'
import { Route as SchemaResourceResourceResourceIdDetailTabRouteImport } from './routes/$schema/resource/$resource/$resourceId/detail.$tab'
import { Route as SchemaResourceResourceResourceIdDetailTabSheetRouteImport } from './routes/$schema/resource/$resource/$resourceId/detail.$tab.sheet'

const StorageRouteRoute = StorageRouteRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRouteRoute = CoreRouteRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRouteRoute = AiRouteRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRouteRoute = SchemaRouteRouteImport.update({
  id: '/$schema',
  path: '/$schema',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageIndexRoute = StorageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorageRouteRoute,
} as any)
const CoreIndexRoute = CoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRouteRoute,
} as any)
const SchemaIndexRoute = SchemaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchemaRouteRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountRolesPermissionsRoute = AccountRolesPermissionsRouteImport.update({
  id: '/roles-permissions',
  path: '/roles-permissions',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountIdentitiesRoute = AccountIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => AccountRouteRoute,
} as any)
const StorageBucketIdRouteRoute = StorageBucketIdRouteRouteImport.update({
  id: '/$bucketId',
  path: '/$bucketId',
  getParentRoute: () => StorageRouteRoute,
} as any)
const StorageBucketIdIndexRoute = StorageBucketIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorageBucketIdRouteRoute,
} as any)
const CoreUsersIndexRoute = CoreUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreAudit_logsIndexRoute = CoreAudit_logsIndexRouteImport.update({
  id: '/audit_logs/',
  path: '/audit_logs/',
  getParentRoute: () => CoreRouteRoute,
} as any)
const SchemaTemplateIndexRoute = SchemaTemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => SchemaRouteRoute,
} as any)
const SchemaReportIndexRoute = SchemaReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => SchemaRouteRoute,
} as any)
const SchemaDashboardIndexRoute = SchemaDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => SchemaRouteRoute,
} as any)
const SchemaChartIndexRoute = SchemaChartIndexRouteImport.update({
  id: '/chart/',
  path: '/chart/',
  getParentRoute: () => SchemaRouteRoute,
} as any)
const StorageBucketIdSplatRoute = StorageBucketIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => StorageBucketIdRouteRoute,
} as any)
const CoreUsersNewRoute = CoreUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreUsersInviteRoute = CoreUsersInviteRouteImport.update({
  id: '/users/invite',
  path: '/users/invite',
  getParentRoute: () => CoreRouteRoute,
} as any)
const CoreAudit_logsAuditLogIdRoute =
  CoreAudit_logsAuditLogIdRouteImport.update({
    id: '/audit_logs/$auditLogId',
    path: '/audit_logs/$auditLogId',
    getParentRoute: () => CoreRouteRoute,
  } as any)
const CoreUsersUserIdRouteRoute = CoreUsersUserIdRouteRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => CoreRouteRoute,
} as any)
const SchemaResourceResourceRouteRoute =
  SchemaResourceResourceRouteRouteImport.update({
    id: '/resource/$resource',
    path: '/resource/$resource',
    getParentRoute: () => SchemaRouteRoute,
  } as any)
const CoreUsersUserIdIndexRoute = CoreUsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoreUsersUserIdRouteRoute,
} as any)
const SchemaTemplateTemplateIndexRoute =
  SchemaTemplateTemplateIndexRouteImport.update({
    id: '/template/$template/',
    path: '/template/$template/',
    getParentRoute: () => SchemaRouteRoute,
  } as any)
const SchemaResourceResourceIndexRoute =
  SchemaResourceResourceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaReportReportIndexRoute = SchemaReportReportIndexRouteImport.update({
  id: '/report/$report/',
  path: '/report/$report/',
  getParentRoute: () => SchemaRouteRoute,
} as any)
const CoreUsersUserIdSecurityRoute = CoreUsersUserIdSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => CoreUsersUserIdRouteRoute,
} as any)
const CoreUsersUserIdEditRoute = CoreUsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CoreUsersUserIdRouteRoute,
} as any)
const CoreUsersUserIdDangerRoute = CoreUsersUserIdDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => CoreUsersUserIdRouteRoute,
} as any)
const SchemaResourceResourceTableRoute =
  SchemaResourceResourceTableRouteImport.update({
    id: '/table',
    path: '/table',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceSingleRoute =
  SchemaResourceResourceSingleRouteImport.update({
    id: '/single',
    path: '/single',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceNewRoute =
  SchemaResourceResourceNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceGridRoute =
  SchemaResourceResourceGridRouteImport.update({
    id: '/grid',
    path: '/grid',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceDefinitionRoute =
  SchemaResourceResourceDefinitionRouteImport.update({
    id: '/definition',
    path: '/definition',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceTreeTreeIdRoute =
  SchemaResourceResourceTreeTreeIdRouteImport.update({
    id: '/tree/$treeId',
    path: '/tree/$treeId',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceTableSheetRoute =
  SchemaResourceResourceTableSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => SchemaResourceResourceTableRoute,
  } as any)
const SchemaResourceResourceListListIdRoute =
  SchemaResourceResourceListListIdRouteImport.update({
    id: '/list/$listId',
    path: '/list/$listId',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceKanbanKanbanIdRoute =
  SchemaResourceResourceKanbanKanbanIdRouteImport.update({
    id: '/kanban/$kanbanId',
    path: '/kanban/$kanbanId',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceGridSheetRoute =
  SchemaResourceResourceGridSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => SchemaResourceResourceGridRoute,
  } as any)
const SchemaResourceResourceGalleryGalleryIdRoute =
  SchemaResourceResourceGalleryGalleryIdRouteImport.update({
    id: '/gallery/$galleryId',
    path: '/gallery/$galleryId',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceCalendarCalendarIdRoute =
  SchemaResourceResourceCalendarCalendarIdRouteImport.update({
    id: '/calendar/$calendarId',
    path: '/calendar/$calendarId',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceResourceIdDetailRoute =
  SchemaResourceResourceResourceIdDetailRouteImport.update({
    id: '/$resourceId/detail',
    path: '/$resourceId/detail',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceResourceIdCommentRoute =
  SchemaResourceResourceResourceIdCommentRouteImport.update({
    id: '/$resourceId/comment',
    path: '/$resourceId/comment',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceResourceIdAuditRoute =
  SchemaResourceResourceResourceIdAuditRouteImport.update({
    id: '/$resourceId/audit',
    path: '/$resourceId/audit',
    getParentRoute: () => SchemaResourceResourceRouteRoute,
  } as any)
const SchemaResourceResourceResourceIdDetailIndexRoute =
  SchemaResourceResourceResourceIdDetailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SchemaResourceResourceResourceIdDetailRoute,
  } as any)
const SchemaResourceResourceTreeTreeIdSheetRoute =
  SchemaResourceResourceTreeTreeIdSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => SchemaResourceResourceTreeTreeIdRoute,
  } as any)
const SchemaResourceResourceListListIdSheetRoute =
  SchemaResourceResourceListListIdSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => SchemaResourceResourceListListIdRoute,
  } as any)
const SchemaResourceResourceKanbanKanbanIdSheetRoute =
  SchemaResourceResourceKanbanKanbanIdSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => SchemaResourceResourceKanbanKanbanIdRoute,
  } as any)
const SchemaResourceResourceGalleryGalleryIdSheetRoute =
  SchemaResourceResourceGalleryGalleryIdSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => SchemaResourceResourceGalleryGalleryIdRoute,
  } as any)
const SchemaResourceResourceCalendarCalendarIdSheetRoute =
  SchemaResourceResourceCalendarCalendarIdSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => SchemaResourceResourceCalendarCalendarIdRoute,
  } as any)
const SchemaResourceResourceResourceIdDetailSheetRoute =
  SchemaResourceResourceResourceIdDetailSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => SchemaResourceResourceResourceIdDetailRoute,
  } as any)
const SchemaResourceResourceResourceIdDetailTabRoute =
  SchemaResourceResourceResourceIdDetailTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => SchemaResourceResourceResourceIdDetailRoute,
  } as any)
const SchemaResourceResourceResourceIdDetailTabSheetRoute =
  SchemaResourceResourceResourceIdDetailTabSheetRouteImport.update({
    id: '/sheet',
    path: '/sheet',
    getParentRoute: () => SchemaResourceResourceResourceIdDetailTabRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$schema': typeof SchemaRouteRouteWithChildren
  '/account': typeof AccountRouteRouteWithChildren
  '/ai': typeof AiRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/core': typeof CoreRouteRouteWithChildren
  '/storage': typeof StorageRouteRouteWithChildren
  '/storage/$bucketId': typeof StorageBucketIdRouteRouteWithChildren
  '/account/identities': typeof AccountIdentitiesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/roles-permissions': typeof AccountRolesPermissionsRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/$schema/': typeof SchemaIndexRoute
  '/ai/': typeof AiIndexRoute
  '/core/': typeof CoreIndexRoute
  '/storage/': typeof StorageIndexRoute
  '/$schema/resource/$resource': typeof SchemaResourceResourceRouteRouteWithChildren
  '/core/users/$userId': typeof CoreUsersUserIdRouteRouteWithChildren
  '/core/audit_logs/$auditLogId': typeof CoreAudit_logsAuditLogIdRoute
  '/core/users/invite': typeof CoreUsersInviteRoute
  '/core/users/new': typeof CoreUsersNewRoute
  '/storage/$bucketId/$': typeof StorageBucketIdSplatRoute
  '/$schema/chart/': typeof SchemaChartIndexRoute
  '/$schema/dashboard/': typeof SchemaDashboardIndexRoute
  '/$schema/report/': typeof SchemaReportIndexRoute
  '/$schema/template/': typeof SchemaTemplateIndexRoute
  '/core/audit_logs/': typeof CoreAudit_logsIndexRoute
  '/core/users/': typeof CoreUsersIndexRoute
  '/storage/$bucketId/': typeof StorageBucketIdIndexRoute
  '/$schema/resource/$resource/definition': typeof SchemaResourceResourceDefinitionRoute
  '/$schema/resource/$resource/grid': typeof SchemaResourceResourceGridRouteWithChildren
  '/$schema/resource/$resource/new': typeof SchemaResourceResourceNewRoute
  '/$schema/resource/$resource/single': typeof SchemaResourceResourceSingleRoute
  '/$schema/resource/$resource/table': typeof SchemaResourceResourceTableRouteWithChildren
  '/core/users/$userId/danger': typeof CoreUsersUserIdDangerRoute
  '/core/users/$userId/edit': typeof CoreUsersUserIdEditRoute
  '/core/users/$userId/security': typeof CoreUsersUserIdSecurityRoute
  '/$schema/report/$report/': typeof SchemaReportReportIndexRoute
  '/$schema/resource/$resource/': typeof SchemaResourceResourceIndexRoute
  '/$schema/template/$template/': typeof SchemaTemplateTemplateIndexRoute
  '/core/users/$userId/': typeof CoreUsersUserIdIndexRoute
  '/$schema/resource/$resource/$resourceId/audit': typeof SchemaResourceResourceResourceIdAuditRoute
  '/$schema/resource/$resource/$resourceId/comment': typeof SchemaResourceResourceResourceIdCommentRoute
  '/$schema/resource/$resource/$resourceId/detail': typeof SchemaResourceResourceResourceIdDetailRouteWithChildren
  '/$schema/resource/$resource/calendar/$calendarId': typeof SchemaResourceResourceCalendarCalendarIdRouteWithChildren
  '/$schema/resource/$resource/gallery/$galleryId': typeof SchemaResourceResourceGalleryGalleryIdRouteWithChildren
  '/$schema/resource/$resource/grid/sheet': typeof SchemaResourceResourceGridSheetRoute
  '/$schema/resource/$resource/kanban/$kanbanId': typeof SchemaResourceResourceKanbanKanbanIdRouteWithChildren
  '/$schema/resource/$resource/list/$listId': typeof SchemaResourceResourceListListIdRouteWithChildren
  '/$schema/resource/$resource/table/sheet': typeof SchemaResourceResourceTableSheetRoute
  '/$schema/resource/$resource/tree/$treeId': typeof SchemaResourceResourceTreeTreeIdRouteWithChildren
  '/$schema/resource/$resource/$resourceId/detail/$tab': typeof SchemaResourceResourceResourceIdDetailTabRouteWithChildren
  '/$schema/resource/$resource/$resourceId/detail/sheet': typeof SchemaResourceResourceResourceIdDetailSheetRoute
  '/$schema/resource/$resource/calendar/$calendarId/sheet': typeof SchemaResourceResourceCalendarCalendarIdSheetRoute
  '/$schema/resource/$resource/gallery/$galleryId/sheet': typeof SchemaResourceResourceGalleryGalleryIdSheetRoute
  '/$schema/resource/$resource/kanban/$kanbanId/sheet': typeof SchemaResourceResourceKanbanKanbanIdSheetRoute
  '/$schema/resource/$resource/list/$listId/sheet': typeof SchemaResourceResourceListListIdSheetRoute
  '/$schema/resource/$resource/tree/$treeId/sheet': typeof SchemaResourceResourceTreeTreeIdSheetRoute
  '/$schema/resource/$resource/$resourceId/detail/': typeof SchemaResourceResourceResourceIdDetailIndexRoute
  '/$schema/resource/$resource/$resourceId/detail/$tab/sheet': typeof SchemaResourceResourceResourceIdDetailTabSheetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/account/identities': typeof AccountIdentitiesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/roles-permissions': typeof AccountRolesPermissionsRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/$schema': typeof SchemaIndexRoute
  '/ai': typeof AiIndexRoute
  '/core': typeof CoreIndexRoute
  '/storage': typeof StorageIndexRoute
  '/core/audit_logs/$auditLogId': typeof CoreAudit_logsAuditLogIdRoute
  '/core/users/invite': typeof CoreUsersInviteRoute
  '/core/users/new': typeof CoreUsersNewRoute
  '/storage/$bucketId/$': typeof StorageBucketIdSplatRoute
  '/$schema/chart': typeof SchemaChartIndexRoute
  '/$schema/dashboard': typeof SchemaDashboardIndexRoute
  '/$schema/report': typeof SchemaReportIndexRoute
  '/$schema/template': typeof SchemaTemplateIndexRoute
  '/core/audit_logs': typeof CoreAudit_logsIndexRoute
  '/core/users': typeof CoreUsersIndexRoute
  '/storage/$bucketId': typeof StorageBucketIdIndexRoute
  '/$schema/resource/$resource/definition': typeof SchemaResourceResourceDefinitionRoute
  '/$schema/resource/$resource/grid': typeof SchemaResourceResourceGridRouteWithChildren
  '/$schema/resource/$resource/new': typeof SchemaResourceResourceNewRoute
  '/$schema/resource/$resource/single': typeof SchemaResourceResourceSingleRoute
  '/$schema/resource/$resource/table': typeof SchemaResourceResourceTableRouteWithChildren
  '/core/users/$userId/danger': typeof CoreUsersUserIdDangerRoute
  '/core/users/$userId/edit': typeof CoreUsersUserIdEditRoute
  '/core/users/$userId/security': typeof CoreUsersUserIdSecurityRoute
  '/$schema/report/$report': typeof SchemaReportReportIndexRoute
  '/$schema/resource/$resource': typeof SchemaResourceResourceIndexRoute
  '/$schema/template/$template': typeof SchemaTemplateTemplateIndexRoute
  '/core/users/$userId': typeof CoreUsersUserIdIndexRoute
  '/$schema/resource/$resource/$resourceId/audit': typeof SchemaResourceResourceResourceIdAuditRoute
  '/$schema/resource/$resource/$resourceId/comment': typeof SchemaResourceResourceResourceIdCommentRoute
  '/$schema/resource/$resource/calendar/$calendarId': typeof SchemaResourceResourceCalendarCalendarIdRouteWithChildren
  '/$schema/resource/$resource/gallery/$galleryId': typeof SchemaResourceResourceGalleryGalleryIdRouteWithChildren
  '/$schema/resource/$resource/grid/sheet': typeof SchemaResourceResourceGridSheetRoute
  '/$schema/resource/$resource/kanban/$kanbanId': typeof SchemaResourceResourceKanbanKanbanIdRouteWithChildren
  '/$schema/resource/$resource/list/$listId': typeof SchemaResourceResourceListListIdRouteWithChildren
  '/$schema/resource/$resource/table/sheet': typeof SchemaResourceResourceTableSheetRoute
  '/$schema/resource/$resource/tree/$treeId': typeof SchemaResourceResourceTreeTreeIdRouteWithChildren
  '/$schema/resource/$resource/$resourceId/detail/$tab': typeof SchemaResourceResourceResourceIdDetailTabRouteWithChildren
  '/$schema/resource/$resource/$resourceId/detail/sheet': typeof SchemaResourceResourceResourceIdDetailSheetRoute
  '/$schema/resource/$resource/calendar/$calendarId/sheet': typeof SchemaResourceResourceCalendarCalendarIdSheetRoute
  '/$schema/resource/$resource/gallery/$galleryId/sheet': typeof SchemaResourceResourceGalleryGalleryIdSheetRoute
  '/$schema/resource/$resource/kanban/$kanbanId/sheet': typeof SchemaResourceResourceKanbanKanbanIdSheetRoute
  '/$schema/resource/$resource/list/$listId/sheet': typeof SchemaResourceResourceListListIdSheetRoute
  '/$schema/resource/$resource/tree/$treeId/sheet': typeof SchemaResourceResourceTreeTreeIdSheetRoute
  '/$schema/resource/$resource/$resourceId/detail': typeof SchemaResourceResourceResourceIdDetailIndexRoute
  '/$schema/resource/$resource/$resourceId/detail/$tab/sheet': typeof SchemaResourceResourceResourceIdDetailTabSheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$schema': typeof SchemaRouteRouteWithChildren
  '/account': typeof AccountRouteRouteWithChildren
  '/ai': typeof AiRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/core': typeof CoreRouteRouteWithChildren
  '/storage': typeof StorageRouteRouteWithChildren
  '/storage/$bucketId': typeof StorageBucketIdRouteRouteWithChildren
  '/account/identities': typeof AccountIdentitiesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/roles-permissions': typeof AccountRolesPermissionsRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/$schema/': typeof SchemaIndexRoute
  '/ai/': typeof AiIndexRoute
  '/core/': typeof CoreIndexRoute
  '/storage/': typeof StorageIndexRoute
  '/$schema/resource/$resource': typeof SchemaResourceResourceRouteRouteWithChildren
  '/core/users/$userId': typeof CoreUsersUserIdRouteRouteWithChildren
  '/core/audit_logs/$auditLogId': typeof CoreAudit_logsAuditLogIdRoute
  '/core/users/invite': typeof CoreUsersInviteRoute
  '/core/users/new': typeof CoreUsersNewRoute
  '/storage/$bucketId/$': typeof StorageBucketIdSplatRoute
  '/$schema/chart/': typeof SchemaChartIndexRoute
  '/$schema/dashboard/': typeof SchemaDashboardIndexRoute
  '/$schema/report/': typeof SchemaReportIndexRoute
  '/$schema/template/': typeof SchemaTemplateIndexRoute
  '/core/audit_logs/': typeof CoreAudit_logsIndexRoute
  '/core/users/': typeof CoreUsersIndexRoute
  '/storage/$bucketId/': typeof StorageBucketIdIndexRoute
  '/$schema/resource/$resource/definition': typeof SchemaResourceResourceDefinitionRoute
  '/$schema/resource/$resource/grid': typeof SchemaResourceResourceGridRouteWithChildren
  '/$schema/resource/$resource/new': typeof SchemaResourceResourceNewRoute
  '/$schema/resource/$resource/single': typeof SchemaResourceResourceSingleRoute
  '/$schema/resource/$resource/table': typeof SchemaResourceResourceTableRouteWithChildren
  '/core/users/$userId/danger': typeof CoreUsersUserIdDangerRoute
  '/core/users/$userId/edit': typeof CoreUsersUserIdEditRoute
  '/core/users/$userId/security': typeof CoreUsersUserIdSecurityRoute
  '/$schema/report/$report/': typeof SchemaReportReportIndexRoute
  '/$schema/resource/$resource/': typeof SchemaResourceResourceIndexRoute
  '/$schema/template/$template/': typeof SchemaTemplateTemplateIndexRoute
  '/core/users/$userId/': typeof CoreUsersUserIdIndexRoute
  '/$schema/resource/$resource/$resourceId/audit': typeof SchemaResourceResourceResourceIdAuditRoute
  '/$schema/resource/$resource/$resourceId/comment': typeof SchemaResourceResourceResourceIdCommentRoute
  '/$schema/resource/$resource/$resourceId/detail': typeof SchemaResourceResourceResourceIdDetailRouteWithChildren
  '/$schema/resource/$resource/calendar/$calendarId': typeof SchemaResourceResourceCalendarCalendarIdRouteWithChildren
  '/$schema/resource/$resource/gallery/$galleryId': typeof SchemaResourceResourceGalleryGalleryIdRouteWithChildren
  '/$schema/resource/$resource/grid/sheet': typeof SchemaResourceResourceGridSheetRoute
  '/$schema/resource/$resource/kanban/$kanbanId': typeof SchemaResourceResourceKanbanKanbanIdRouteWithChildren
  '/$schema/resource/$resource/list/$listId': typeof SchemaResourceResourceListListIdRouteWithChildren
  '/$schema/resource/$resource/table/sheet': typeof SchemaResourceResourceTableSheetRoute
  '/$schema/resource/$resource/tree/$treeId': typeof SchemaResourceResourceTreeTreeIdRouteWithChildren
  '/$schema/resource/$resource/$resourceId/detail/$tab': typeof SchemaResourceResourceResourceIdDetailTabRouteWithChildren
  '/$schema/resource/$resource/$resourceId/detail/sheet': typeof SchemaResourceResourceResourceIdDetailSheetRoute
  '/$schema/resource/$resource/calendar/$calendarId/sheet': typeof SchemaResourceResourceCalendarCalendarIdSheetRoute
  '/$schema/resource/$resource/gallery/$galleryId/sheet': typeof SchemaResourceResourceGalleryGalleryIdSheetRoute
  '/$schema/resource/$resource/kanban/$kanbanId/sheet': typeof SchemaResourceResourceKanbanKanbanIdSheetRoute
  '/$schema/resource/$resource/list/$listId/sheet': typeof SchemaResourceResourceListListIdSheetRoute
  '/$schema/resource/$resource/tree/$treeId/sheet': typeof SchemaResourceResourceTreeTreeIdSheetRoute
  '/$schema/resource/$resource/$resourceId/detail/': typeof SchemaResourceResourceResourceIdDetailIndexRoute
  '/$schema/resource/$resource/$resourceId/detail/$tab/sheet': typeof SchemaResourceResourceResourceIdDetailTabSheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$schema'
    | '/account'
    | '/ai'
    | '/auth'
    | '/core'
    | '/storage'
    | '/storage/$bucketId'
    | '/account/identities'
    | '/account/profile'
    | '/account/roles-permissions'
    | '/account/security'
    | '/auth/forgot-password'
    | '/auth/mfa'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/update-password'
    | '/$schema/'
    | '/ai/'
    | '/core/'
    | '/storage/'
    | '/$schema/resource/$resource'
    | '/core/users/$userId'
    | '/core/audit_logs/$auditLogId'
    | '/core/users/invite'
    | '/core/users/new'
    | '/storage/$bucketId/$'
    | '/$schema/chart/'
    | '/$schema/dashboard/'
    | '/$schema/report/'
    | '/$schema/template/'
    | '/core/audit_logs/'
    | '/core/users/'
    | '/storage/$bucketId/'
    | '/$schema/resource/$resource/definition'
    | '/$schema/resource/$resource/grid'
    | '/$schema/resource/$resource/new'
    | '/$schema/resource/$resource/single'
    | '/$schema/resource/$resource/table'
    | '/core/users/$userId/danger'
    | '/core/users/$userId/edit'
    | '/core/users/$userId/security'
    | '/$schema/report/$report/'
    | '/$schema/resource/$resource/'
    | '/$schema/template/$template/'
    | '/core/users/$userId/'
    | '/$schema/resource/$resource/$resourceId/audit'
    | '/$schema/resource/$resource/$resourceId/comment'
    | '/$schema/resource/$resource/$resourceId/detail'
    | '/$schema/resource/$resource/calendar/$calendarId'
    | '/$schema/resource/$resource/gallery/$galleryId'
    | '/$schema/resource/$resource/grid/sheet'
    | '/$schema/resource/$resource/kanban/$kanbanId'
    | '/$schema/resource/$resource/list/$listId'
    | '/$schema/resource/$resource/table/sheet'
    | '/$schema/resource/$resource/tree/$treeId'
    | '/$schema/resource/$resource/$resourceId/detail/$tab'
    | '/$schema/resource/$resource/$resourceId/detail/sheet'
    | '/$schema/resource/$resource/calendar/$calendarId/sheet'
    | '/$schema/resource/$resource/gallery/$galleryId/sheet'
    | '/$schema/resource/$resource/kanban/$kanbanId/sheet'
    | '/$schema/resource/$resource/list/$listId/sheet'
    | '/$schema/resource/$resource/tree/$treeId/sheet'
    | '/$schema/resource/$resource/$resourceId/detail/'
    | '/$schema/resource/$resource/$resourceId/detail/$tab/sheet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/account/identities'
    | '/account/profile'
    | '/account/roles-permissions'
    | '/account/security'
    | '/auth/forgot-password'
    | '/auth/mfa'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/update-password'
    | '/$schema'
    | '/ai'
    | '/core'
    | '/storage'
    | '/core/audit_logs/$auditLogId'
    | '/core/users/invite'
    | '/core/users/new'
    | '/storage/$bucketId/$'
    | '/$schema/chart'
    | '/$schema/dashboard'
    | '/$schema/report'
    | '/$schema/template'
    | '/core/audit_logs'
    | '/core/users'
    | '/storage/$bucketId'
    | '/$schema/resource/$resource/definition'
    | '/$schema/resource/$resource/grid'
    | '/$schema/resource/$resource/new'
    | '/$schema/resource/$resource/single'
    | '/$schema/resource/$resource/table'
    | '/core/users/$userId/danger'
    | '/core/users/$userId/edit'
    | '/core/users/$userId/security'
    | '/$schema/report/$report'
    | '/$schema/resource/$resource'
    | '/$schema/template/$template'
    | '/core/users/$userId'
    | '/$schema/resource/$resource/$resourceId/audit'
    | '/$schema/resource/$resource/$resourceId/comment'
    | '/$schema/resource/$resource/calendar/$calendarId'
    | '/$schema/resource/$resource/gallery/$galleryId'
    | '/$schema/resource/$resource/grid/sheet'
    | '/$schema/resource/$resource/kanban/$kanbanId'
    | '/$schema/resource/$resource/list/$listId'
    | '/$schema/resource/$resource/table/sheet'
    | '/$schema/resource/$resource/tree/$treeId'
    | '/$schema/resource/$resource/$resourceId/detail/$tab'
    | '/$schema/resource/$resource/$resourceId/detail/sheet'
    | '/$schema/resource/$resource/calendar/$calendarId/sheet'
    | '/$schema/resource/$resource/gallery/$galleryId/sheet'
    | '/$schema/resource/$resource/kanban/$kanbanId/sheet'
    | '/$schema/resource/$resource/list/$listId/sheet'
    | '/$schema/resource/$resource/tree/$treeId/sheet'
    | '/$schema/resource/$resource/$resourceId/detail'
    | '/$schema/resource/$resource/$resourceId/detail/$tab/sheet'
  id:
    | '__root__'
    | '/'
    | '/$schema'
    | '/account'
    | '/ai'
    | '/auth'
    | '/core'
    | '/storage'
    | '/storage/$bucketId'
    | '/account/identities'
    | '/account/profile'
    | '/account/roles-permissions'
    | '/account/security'
    | '/auth/forgot-password'
    | '/auth/mfa'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/update-password'
    | '/$schema/'
    | '/ai/'
    | '/core/'
    | '/storage/'
    | '/$schema/resource/$resource'
    | '/core/users/$userId'
    | '/core/audit_logs/$auditLogId'
    | '/core/users/invite'
    | '/core/users/new'
    | '/storage/$bucketId/$'
    | '/$schema/chart/'
    | '/$schema/dashboard/'
    | '/$schema/report/'
    | '/$schema/template/'
    | '/core/audit_logs/'
    | '/core/users/'
    | '/storage/$bucketId/'
    | '/$schema/resource/$resource/definition'
    | '/$schema/resource/$resource/grid'
    | '/$schema/resource/$resource/new'
    | '/$schema/resource/$resource/single'
    | '/$schema/resource/$resource/table'
    | '/core/users/$userId/danger'
    | '/core/users/$userId/edit'
    | '/core/users/$userId/security'
    | '/$schema/report/$report/'
    | '/$schema/resource/$resource/'
    | '/$schema/template/$template/'
    | '/core/users/$userId/'
    | '/$schema/resource/$resource/$resourceId/audit'
    | '/$schema/resource/$resource/$resourceId/comment'
    | '/$schema/resource/$resource/$resourceId/detail'
    | '/$schema/resource/$resource/calendar/$calendarId'
    | '/$schema/resource/$resource/gallery/$galleryId'
    | '/$schema/resource/$resource/grid/sheet'
    | '/$schema/resource/$resource/kanban/$kanbanId'
    | '/$schema/resource/$resource/list/$listId'
    | '/$schema/resource/$resource/table/sheet'
    | '/$schema/resource/$resource/tree/$treeId'
    | '/$schema/resource/$resource/$resourceId/detail/$tab'
    | '/$schema/resource/$resource/$resourceId/detail/sheet'
    | '/$schema/resource/$resource/calendar/$calendarId/sheet'
    | '/$schema/resource/$resource/gallery/$galleryId/sheet'
    | '/$schema/resource/$resource/kanban/$kanbanId/sheet'
    | '/$schema/resource/$resource/list/$listId/sheet'
    | '/$schema/resource/$resource/tree/$treeId/sheet'
    | '/$schema/resource/$resource/$resourceId/detail/'
    | '/$schema/resource/$resource/$resourceId/detail/$tab/sheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchemaRouteRoute: typeof SchemaRouteRouteWithChildren
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AiRouteRoute: typeof AiRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CoreRouteRoute: typeof CoreRouteRouteWithChildren
  StorageRouteRoute: typeof StorageRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core': {
      id: '/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof CoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$schema': {
      id: '/$schema'
      path: '/$schema'
      fullPath: '/$schema'
      preLoaderRoute: typeof SchemaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/': {
      id: '/storage/'
      path: '/'
      fullPath: '/storage/'
      preLoaderRoute: typeof StorageIndexRouteImport
      parentRoute: typeof StorageRouteRoute
    }
    '/core/': {
      id: '/core/'
      path: '/'
      fullPath: '/core/'
      preLoaderRoute: typeof CoreIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRouteRoute
    }
    '/$schema/': {
      id: '/$schema/'
      path: '/'
      fullPath: '/$schema/'
      preLoaderRoute: typeof SchemaIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/roles-permissions': {
      id: '/account/roles-permissions'
      path: '/roles-permissions'
      fullPath: '/account/roles-permissions'
      preLoaderRoute: typeof AccountRolesPermissionsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/identities': {
      id: '/account/identities'
      path: '/identities'
      fullPath: '/account/identities'
      preLoaderRoute: typeof AccountIdentitiesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/storage/$bucketId': {
      id: '/storage/$bucketId'
      path: '/$bucketId'
      fullPath: '/storage/$bucketId'
      preLoaderRoute: typeof StorageBucketIdRouteRouteImport
      parentRoute: typeof StorageRouteRoute
    }
    '/storage/$bucketId/': {
      id: '/storage/$bucketId/'
      path: '/'
      fullPath: '/storage/$bucketId/'
      preLoaderRoute: typeof StorageBucketIdIndexRouteImport
      parentRoute: typeof StorageBucketIdRouteRoute
    }
    '/core/users/': {
      id: '/core/users/'
      path: '/users'
      fullPath: '/core/users/'
      preLoaderRoute: typeof CoreUsersIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/core/audit_logs/': {
      id: '/core/audit_logs/'
      path: '/audit_logs'
      fullPath: '/core/audit_logs/'
      preLoaderRoute: typeof CoreAudit_logsIndexRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/$schema/template/': {
      id: '/$schema/template/'
      path: '/template'
      fullPath: '/$schema/template/'
      preLoaderRoute: typeof SchemaTemplateIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    '/$schema/report/': {
      id: '/$schema/report/'
      path: '/report'
      fullPath: '/$schema/report/'
      preLoaderRoute: typeof SchemaReportIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    '/$schema/dashboard/': {
      id: '/$schema/dashboard/'
      path: '/dashboard'
      fullPath: '/$schema/dashboard/'
      preLoaderRoute: typeof SchemaDashboardIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    '/$schema/chart/': {
      id: '/$schema/chart/'
      path: '/chart'
      fullPath: '/$schema/chart/'
      preLoaderRoute: typeof SchemaChartIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    '/storage/$bucketId/$': {
      id: '/storage/$bucketId/$'
      path: '/$'
      fullPath: '/storage/$bucketId/$'
      preLoaderRoute: typeof StorageBucketIdSplatRouteImport
      parentRoute: typeof StorageBucketIdRouteRoute
    }
    '/core/users/new': {
      id: '/core/users/new'
      path: '/users/new'
      fullPath: '/core/users/new'
      preLoaderRoute: typeof CoreUsersNewRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/core/users/invite': {
      id: '/core/users/invite'
      path: '/users/invite'
      fullPath: '/core/users/invite'
      preLoaderRoute: typeof CoreUsersInviteRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/core/audit_logs/$auditLogId': {
      id: '/core/audit_logs/$auditLogId'
      path: '/audit_logs/$auditLogId'
      fullPath: '/core/audit_logs/$auditLogId'
      preLoaderRoute: typeof CoreAudit_logsAuditLogIdRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/core/users/$userId': {
      id: '/core/users/$userId'
      path: '/users/$userId'
      fullPath: '/core/users/$userId'
      preLoaderRoute: typeof CoreUsersUserIdRouteRouteImport
      parentRoute: typeof CoreRouteRoute
    }
    '/$schema/resource/$resource': {
      id: '/$schema/resource/$resource'
      path: '/resource/$resource'
      fullPath: '/$schema/resource/$resource'
      preLoaderRoute: typeof SchemaResourceResourceRouteRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    '/core/users/$userId/': {
      id: '/core/users/$userId/'
      path: '/'
      fullPath: '/core/users/$userId/'
      preLoaderRoute: typeof CoreUsersUserIdIndexRouteImport
      parentRoute: typeof CoreUsersUserIdRouteRoute
    }
    '/$schema/template/$template/': {
      id: '/$schema/template/$template/'
      path: '/template/$template'
      fullPath: '/$schema/template/$template/'
      preLoaderRoute: typeof SchemaTemplateTemplateIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    '/$schema/resource/$resource/': {
      id: '/$schema/resource/$resource/'
      path: '/'
      fullPath: '/$schema/resource/$resource/'
      preLoaderRoute: typeof SchemaResourceResourceIndexRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/report/$report/': {
      id: '/$schema/report/$report/'
      path: '/report/$report'
      fullPath: '/$schema/report/$report/'
      preLoaderRoute: typeof SchemaReportReportIndexRouteImport
      parentRoute: typeof SchemaRouteRoute
    }
    '/core/users/$userId/security': {
      id: '/core/users/$userId/security'
      path: '/security'
      fullPath: '/core/users/$userId/security'
      preLoaderRoute: typeof CoreUsersUserIdSecurityRouteImport
      parentRoute: typeof CoreUsersUserIdRouteRoute
    }
    '/core/users/$userId/edit': {
      id: '/core/users/$userId/edit'
      path: '/edit'
      fullPath: '/core/users/$userId/edit'
      preLoaderRoute: typeof CoreUsersUserIdEditRouteImport
      parentRoute: typeof CoreUsersUserIdRouteRoute
    }
    '/core/users/$userId/danger': {
      id: '/core/users/$userId/danger'
      path: '/danger'
      fullPath: '/core/users/$userId/danger'
      preLoaderRoute: typeof CoreUsersUserIdDangerRouteImport
      parentRoute: typeof CoreUsersUserIdRouteRoute
    }
    '/$schema/resource/$resource/table': {
      id: '/$schema/resource/$resource/table'
      path: '/table'
      fullPath: '/$schema/resource/$resource/table'
      preLoaderRoute: typeof SchemaResourceResourceTableRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/single': {
      id: '/$schema/resource/$resource/single'
      path: '/single'
      fullPath: '/$schema/resource/$resource/single'
      preLoaderRoute: typeof SchemaResourceResourceSingleRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/new': {
      id: '/$schema/resource/$resource/new'
      path: '/new'
      fullPath: '/$schema/resource/$resource/new'
      preLoaderRoute: typeof SchemaResourceResourceNewRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/grid': {
      id: '/$schema/resource/$resource/grid'
      path: '/grid'
      fullPath: '/$schema/resource/$resource/grid'
      preLoaderRoute: typeof SchemaResourceResourceGridRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/definition': {
      id: '/$schema/resource/$resource/definition'
      path: '/definition'
      fullPath: '/$schema/resource/$resource/definition'
      preLoaderRoute: typeof SchemaResourceResourceDefinitionRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/tree/$treeId': {
      id: '/$schema/resource/$resource/tree/$treeId'
      path: '/tree/$treeId'
      fullPath: '/$schema/resource/$resource/tree/$treeId'
      preLoaderRoute: typeof SchemaResourceResourceTreeTreeIdRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/table/sheet': {
      id: '/$schema/resource/$resource/table/sheet'
      path: '/sheet'
      fullPath: '/$schema/resource/$resource/table/sheet'
      preLoaderRoute: typeof SchemaResourceResourceTableSheetRouteImport
      parentRoute: typeof SchemaResourceResourceTableRoute
    }
    '/$schema/resource/$resource/list/$listId': {
      id: '/$schema/resource/$resource/list/$listId'
      path: '/list/$listId'
      fullPath: '/$schema/resource/$resource/list/$listId'
      preLoaderRoute: typeof SchemaResourceResourceListListIdRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/kanban/$kanbanId': {
      id: '/$schema/resource/$resource/kanban/$kanbanId'
      path: '/kanban/$kanbanId'
      fullPath: '/$schema/resource/$resource/kanban/$kanbanId'
      preLoaderRoute: typeof SchemaResourceResourceKanbanKanbanIdRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/grid/sheet': {
      id: '/$schema/resource/$resource/grid/sheet'
      path: '/sheet'
      fullPath: '/$schema/resource/$resource/grid/sheet'
      preLoaderRoute: typeof SchemaResourceResourceGridSheetRouteImport
      parentRoute: typeof SchemaResourceResourceGridRoute
    }
    '/$schema/resource/$resource/gallery/$galleryId': {
      id: '/$schema/resource/$resource/gallery/$galleryId'
      path: '/gallery/$galleryId'
      fullPath: '/$schema/resource/$resource/gallery/$galleryId'
      preLoaderRoute: typeof SchemaResourceResourceGalleryGalleryIdRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/calendar/$calendarId': {
      id: '/$schema/resource/$resource/calendar/$calendarId'
      path: '/calendar/$calendarId'
      fullPath: '/$schema/resource/$resource/calendar/$calendarId'
      preLoaderRoute: typeof SchemaResourceResourceCalendarCalendarIdRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/$resourceId/detail': {
      id: '/$schema/resource/$resource/$resourceId/detail'
      path: '/$resourceId/detail'
      fullPath: '/$schema/resource/$resource/$resourceId/detail'
      preLoaderRoute: typeof SchemaResourceResourceResourceIdDetailRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/$resourceId/comment': {
      id: '/$schema/resource/$resource/$resourceId/comment'
      path: '/$resourceId/comment'
      fullPath: '/$schema/resource/$resource/$resourceId/comment'
      preLoaderRoute: typeof SchemaResourceResourceResourceIdCommentRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/$resourceId/audit': {
      id: '/$schema/resource/$resource/$resourceId/audit'
      path: '/$resourceId/audit'
      fullPath: '/$schema/resource/$resource/$resourceId/audit'
      preLoaderRoute: typeof SchemaResourceResourceResourceIdAuditRouteImport
      parentRoute: typeof SchemaResourceResourceRouteRoute
    }
    '/$schema/resource/$resource/$resourceId/detail/': {
      id: '/$schema/resource/$resource/$resourceId/detail/'
      path: '/'
      fullPath: '/$schema/resource/$resource/$resourceId/detail/'
      preLoaderRoute: typeof SchemaResourceResourceResourceIdDetailIndexRouteImport
      parentRoute: typeof SchemaResourceResourceResourceIdDetailRoute
    }
    '/$schema/resource/$resource/tree/$treeId/sheet': {
      id: '/$schema/resource/$resource/tree/$treeId/sheet'
      path: '/sheet'
      fullPath: '/$schema/resource/$resource/tree/$treeId/sheet'
      preLoaderRoute: typeof SchemaResourceResourceTreeTreeIdSheetRouteImport
      parentRoute: typeof SchemaResourceResourceTreeTreeIdRoute
    }
    '/$schema/resource/$resource/list/$listId/sheet': {
      id: '/$schema/resource/$resource/list/$listId/sheet'
      path: '/sheet'
      fullPath: '/$schema/resource/$resource/list/$listId/sheet'
      preLoaderRoute: typeof SchemaResourceResourceListListIdSheetRouteImport
      parentRoute: typeof SchemaResourceResourceListListIdRoute
    }
    '/$schema/resource/$resource/kanban/$kanbanId/sheet': {
      id: '/$schema/resource/$resource/kanban/$kanbanId/sheet'
      path: '/sheet'
      fullPath: '/$schema/resource/$resource/kanban/$kanbanId/sheet'
      preLoaderRoute: typeof SchemaResourceResourceKanbanKanbanIdSheetRouteImport
      parentRoute: typeof SchemaResourceResourceKanbanKanbanIdRoute
    }
    '/$schema/resource/$resource/gallery/$galleryId/sheet': {
      id: '/$schema/resource/$resource/gallery/$galleryId/sheet'
      path: '/sheet'
      fullPath: '/$schema/resource/$resource/gallery/$galleryId/sheet'
      preLoaderRoute: typeof SchemaResourceResourceGalleryGalleryIdSheetRouteImport
      parentRoute: typeof SchemaResourceResourceGalleryGalleryIdRoute
    }
    '/$schema/resource/$resource/calendar/$calendarId/sheet': {
      id: '/$schema/resource/$resource/calendar/$calendarId/sheet'
      path: '/sheet'
      fullPath: '/$schema/resource/$resource/calendar/$calendarId/sheet'
      preLoaderRoute: typeof SchemaResourceResourceCalendarCalendarIdSheetRouteImport
      parentRoute: typeof SchemaResourceResourceCalendarCalendarIdRoute
    }
    '/$schema/resource/$resource/$resourceId/detail/sheet': {
      id: '/$schema/resource/$resource/$resourceId/detail/sheet'
      path: '/sheet'
      fullPath: '/$schema/resource/$resource/$resourceId/detail/sheet'
      preLoaderRoute: typeof SchemaResourceResourceResourceIdDetailSheetRouteImport
      parentRoute: typeof SchemaResourceResourceResourceIdDetailRoute
    }
    '/$schema/resource/$resource/$resourceId/detail/$tab': {
      id: '/$schema/resource/$resource/$resourceId/detail/$tab'
      path: '/$tab'
      fullPath: '/$schema/resource/$resource/$resourceId/detail/$tab'
      preLoaderRoute: typeof SchemaResourceResourceResourceIdDetailTabRouteImport
      parentRoute: typeof SchemaResourceResourceResourceIdDetailRoute
    }
    '/$schema/resource/$resource/$resourceId/detail/$tab/sheet': {
      id: '/$schema/resource/$resource/$resourceId/detail/$tab/sheet'
      path: '/sheet'
      fullPath: '/$schema/resource/$resource/$resourceId/detail/$tab/sheet'
      preLoaderRoute: typeof SchemaResourceResourceResourceIdDetailTabSheetRouteImport
      parentRoute: typeof SchemaResourceResourceResourceIdDetailTabRoute
    }
  }
}

interface SchemaResourceResourceGridRouteChildren {
  SchemaResourceResourceGridSheetRoute: typeof SchemaResourceResourceGridSheetRoute
}

const SchemaResourceResourceGridRouteChildren: SchemaResourceResourceGridRouteChildren =
  {
    SchemaResourceResourceGridSheetRoute: SchemaResourceResourceGridSheetRoute,
  }

const SchemaResourceResourceGridRouteWithChildren =
  SchemaResourceResourceGridRoute._addFileChildren(
    SchemaResourceResourceGridRouteChildren,
  )

interface SchemaResourceResourceTableRouteChildren {
  SchemaResourceResourceTableSheetRoute: typeof SchemaResourceResourceTableSheetRoute
}

const SchemaResourceResourceTableRouteChildren: SchemaResourceResourceTableRouteChildren =
  {
    SchemaResourceResourceTableSheetRoute:
      SchemaResourceResourceTableSheetRoute,
  }

const SchemaResourceResourceTableRouteWithChildren =
  SchemaResourceResourceTableRoute._addFileChildren(
    SchemaResourceResourceTableRouteChildren,
  )

interface SchemaResourceResourceResourceIdDetailTabRouteChildren {
  SchemaResourceResourceResourceIdDetailTabSheetRoute: typeof SchemaResourceResourceResourceIdDetailTabSheetRoute
}

const SchemaResourceResourceResourceIdDetailTabRouteChildren: SchemaResourceResourceResourceIdDetailTabRouteChildren =
  {
    SchemaResourceResourceResourceIdDetailTabSheetRoute:
      SchemaResourceResourceResourceIdDetailTabSheetRoute,
  }

const SchemaResourceResourceResourceIdDetailTabRouteWithChildren =
  SchemaResourceResourceResourceIdDetailTabRoute._addFileChildren(
    SchemaResourceResourceResourceIdDetailTabRouteChildren,
  )

interface SchemaResourceResourceResourceIdDetailRouteChildren {
  SchemaResourceResourceResourceIdDetailTabRoute: typeof SchemaResourceResourceResourceIdDetailTabRouteWithChildren
  SchemaResourceResourceResourceIdDetailSheetRoute: typeof SchemaResourceResourceResourceIdDetailSheetRoute
  SchemaResourceResourceResourceIdDetailIndexRoute: typeof SchemaResourceResourceResourceIdDetailIndexRoute
}

const SchemaResourceResourceResourceIdDetailRouteChildren: SchemaResourceResourceResourceIdDetailRouteChildren =
  {
    SchemaResourceResourceResourceIdDetailTabRoute:
      SchemaResourceResourceResourceIdDetailTabRouteWithChildren,
    SchemaResourceResourceResourceIdDetailSheetRoute:
      SchemaResourceResourceResourceIdDetailSheetRoute,
    SchemaResourceResourceResourceIdDetailIndexRoute:
      SchemaResourceResourceResourceIdDetailIndexRoute,
  }

const SchemaResourceResourceResourceIdDetailRouteWithChildren =
  SchemaResourceResourceResourceIdDetailRoute._addFileChildren(
    SchemaResourceResourceResourceIdDetailRouteChildren,
  )

interface SchemaResourceResourceCalendarCalendarIdRouteChildren {
  SchemaResourceResourceCalendarCalendarIdSheetRoute: typeof SchemaResourceResourceCalendarCalendarIdSheetRoute
}

const SchemaResourceResourceCalendarCalendarIdRouteChildren: SchemaResourceResourceCalendarCalendarIdRouteChildren =
  {
    SchemaResourceResourceCalendarCalendarIdSheetRoute:
      SchemaResourceResourceCalendarCalendarIdSheetRoute,
  }

const SchemaResourceResourceCalendarCalendarIdRouteWithChildren =
  SchemaResourceResourceCalendarCalendarIdRoute._addFileChildren(
    SchemaResourceResourceCalendarCalendarIdRouteChildren,
  )

interface SchemaResourceResourceGalleryGalleryIdRouteChildren {
  SchemaResourceResourceGalleryGalleryIdSheetRoute: typeof SchemaResourceResourceGalleryGalleryIdSheetRoute
}

const SchemaResourceResourceGalleryGalleryIdRouteChildren: SchemaResourceResourceGalleryGalleryIdRouteChildren =
  {
    SchemaResourceResourceGalleryGalleryIdSheetRoute:
      SchemaResourceResourceGalleryGalleryIdSheetRoute,
  }

const SchemaResourceResourceGalleryGalleryIdRouteWithChildren =
  SchemaResourceResourceGalleryGalleryIdRoute._addFileChildren(
    SchemaResourceResourceGalleryGalleryIdRouteChildren,
  )

interface SchemaResourceResourceKanbanKanbanIdRouteChildren {
  SchemaResourceResourceKanbanKanbanIdSheetRoute: typeof SchemaResourceResourceKanbanKanbanIdSheetRoute
}

const SchemaResourceResourceKanbanKanbanIdRouteChildren: SchemaResourceResourceKanbanKanbanIdRouteChildren =
  {
    SchemaResourceResourceKanbanKanbanIdSheetRoute:
      SchemaResourceResourceKanbanKanbanIdSheetRoute,
  }

const SchemaResourceResourceKanbanKanbanIdRouteWithChildren =
  SchemaResourceResourceKanbanKanbanIdRoute._addFileChildren(
    SchemaResourceResourceKanbanKanbanIdRouteChildren,
  )

interface SchemaResourceResourceListListIdRouteChildren {
  SchemaResourceResourceListListIdSheetRoute: typeof SchemaResourceResourceListListIdSheetRoute
}

const SchemaResourceResourceListListIdRouteChildren: SchemaResourceResourceListListIdRouteChildren =
  {
    SchemaResourceResourceListListIdSheetRoute:
      SchemaResourceResourceListListIdSheetRoute,
  }

const SchemaResourceResourceListListIdRouteWithChildren =
  SchemaResourceResourceListListIdRoute._addFileChildren(
    SchemaResourceResourceListListIdRouteChildren,
  )

interface SchemaResourceResourceTreeTreeIdRouteChildren {
  SchemaResourceResourceTreeTreeIdSheetRoute: typeof SchemaResourceResourceTreeTreeIdSheetRoute
}

const SchemaResourceResourceTreeTreeIdRouteChildren: SchemaResourceResourceTreeTreeIdRouteChildren =
  {
    SchemaResourceResourceTreeTreeIdSheetRoute:
      SchemaResourceResourceTreeTreeIdSheetRoute,
  }

const SchemaResourceResourceTreeTreeIdRouteWithChildren =
  SchemaResourceResourceTreeTreeIdRoute._addFileChildren(
    SchemaResourceResourceTreeTreeIdRouteChildren,
  )

interface SchemaResourceResourceRouteRouteChildren {
  SchemaResourceResourceDefinitionRoute: typeof SchemaResourceResourceDefinitionRoute
  SchemaResourceResourceGridRoute: typeof SchemaResourceResourceGridRouteWithChildren
  SchemaResourceResourceNewRoute: typeof SchemaResourceResourceNewRoute
  SchemaResourceResourceSingleRoute: typeof SchemaResourceResourceSingleRoute
  SchemaResourceResourceTableRoute: typeof SchemaResourceResourceTableRouteWithChildren
  SchemaResourceResourceIndexRoute: typeof SchemaResourceResourceIndexRoute
  SchemaResourceResourceResourceIdAuditRoute: typeof SchemaResourceResourceResourceIdAuditRoute
  SchemaResourceResourceResourceIdCommentRoute: typeof SchemaResourceResourceResourceIdCommentRoute
  SchemaResourceResourceResourceIdDetailRoute: typeof SchemaResourceResourceResourceIdDetailRouteWithChildren
  SchemaResourceResourceCalendarCalendarIdRoute: typeof SchemaResourceResourceCalendarCalendarIdRouteWithChildren
  SchemaResourceResourceGalleryGalleryIdRoute: typeof SchemaResourceResourceGalleryGalleryIdRouteWithChildren
  SchemaResourceResourceKanbanKanbanIdRoute: typeof SchemaResourceResourceKanbanKanbanIdRouteWithChildren
  SchemaResourceResourceListListIdRoute: typeof SchemaResourceResourceListListIdRouteWithChildren
  SchemaResourceResourceTreeTreeIdRoute: typeof SchemaResourceResourceTreeTreeIdRouteWithChildren
}

const SchemaResourceResourceRouteRouteChildren: SchemaResourceResourceRouteRouteChildren =
  {
    SchemaResourceResourceDefinitionRoute:
      SchemaResourceResourceDefinitionRoute,
    SchemaResourceResourceGridRoute:
      SchemaResourceResourceGridRouteWithChildren,
    SchemaResourceResourceNewRoute: SchemaResourceResourceNewRoute,
    SchemaResourceResourceSingleRoute: SchemaResourceResourceSingleRoute,
    SchemaResourceResourceTableRoute:
      SchemaResourceResourceTableRouteWithChildren,
    SchemaResourceResourceIndexRoute: SchemaResourceResourceIndexRoute,
    SchemaResourceResourceResourceIdAuditRoute:
      SchemaResourceResourceResourceIdAuditRoute,
    SchemaResourceResourceResourceIdCommentRoute:
      SchemaResourceResourceResourceIdCommentRoute,
    SchemaResourceResourceResourceIdDetailRoute:
      SchemaResourceResourceResourceIdDetailRouteWithChildren,
    SchemaResourceResourceCalendarCalendarIdRoute:
      SchemaResourceResourceCalendarCalendarIdRouteWithChildren,
    SchemaResourceResourceGalleryGalleryIdRoute:
      SchemaResourceResourceGalleryGalleryIdRouteWithChildren,
    SchemaResourceResourceKanbanKanbanIdRoute:
      SchemaResourceResourceKanbanKanbanIdRouteWithChildren,
    SchemaResourceResourceListListIdRoute:
      SchemaResourceResourceListListIdRouteWithChildren,
    SchemaResourceResourceTreeTreeIdRoute:
      SchemaResourceResourceTreeTreeIdRouteWithChildren,
  }

const SchemaResourceResourceRouteRouteWithChildren =
  SchemaResourceResourceRouteRoute._addFileChildren(
    SchemaResourceResourceRouteRouteChildren,
  )

interface SchemaRouteRouteChildren {
  SchemaIndexRoute: typeof SchemaIndexRoute
  SchemaResourceResourceRouteRoute: typeof SchemaResourceResourceRouteRouteWithChildren
  SchemaChartIndexRoute: typeof SchemaChartIndexRoute
  SchemaDashboardIndexRoute: typeof SchemaDashboardIndexRoute
  SchemaReportIndexRoute: typeof SchemaReportIndexRoute
  SchemaTemplateIndexRoute: typeof SchemaTemplateIndexRoute
  SchemaReportReportIndexRoute: typeof SchemaReportReportIndexRoute
  SchemaTemplateTemplateIndexRoute: typeof SchemaTemplateTemplateIndexRoute
}

const SchemaRouteRouteChildren: SchemaRouteRouteChildren = {
  SchemaIndexRoute: SchemaIndexRoute,
  SchemaResourceResourceRouteRoute:
    SchemaResourceResourceRouteRouteWithChildren,
  SchemaChartIndexRoute: SchemaChartIndexRoute,
  SchemaDashboardIndexRoute: SchemaDashboardIndexRoute,
  SchemaReportIndexRoute: SchemaReportIndexRoute,
  SchemaTemplateIndexRoute: SchemaTemplateIndexRoute,
  SchemaReportReportIndexRoute: SchemaReportReportIndexRoute,
  SchemaTemplateTemplateIndexRoute: SchemaTemplateTemplateIndexRoute,
}

const SchemaRouteRouteWithChildren = SchemaRouteRoute._addFileChildren(
  SchemaRouteRouteChildren,
)

interface AccountRouteRouteChildren {
  AccountIdentitiesRoute: typeof AccountIdentitiesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountRolesPermissionsRoute: typeof AccountRolesPermissionsRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountIdentitiesRoute: AccountIdentitiesRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountRolesPermissionsRoute: AccountRolesPermissionsRoute,
  AccountSecurityRoute: AccountSecurityRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AiRouteRouteChildren {
  AiIndexRoute: typeof AiIndexRoute
}

const AiRouteRouteChildren: AiRouteRouteChildren = {
  AiIndexRoute: AiIndexRoute,
}

const AiRouteRouteWithChildren =
  AiRouteRoute._addFileChildren(AiRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CoreUsersUserIdRouteRouteChildren {
  CoreUsersUserIdDangerRoute: typeof CoreUsersUserIdDangerRoute
  CoreUsersUserIdEditRoute: typeof CoreUsersUserIdEditRoute
  CoreUsersUserIdSecurityRoute: typeof CoreUsersUserIdSecurityRoute
  CoreUsersUserIdIndexRoute: typeof CoreUsersUserIdIndexRoute
}

const CoreUsersUserIdRouteRouteChildren: CoreUsersUserIdRouteRouteChildren = {
  CoreUsersUserIdDangerRoute: CoreUsersUserIdDangerRoute,
  CoreUsersUserIdEditRoute: CoreUsersUserIdEditRoute,
  CoreUsersUserIdSecurityRoute: CoreUsersUserIdSecurityRoute,
  CoreUsersUserIdIndexRoute: CoreUsersUserIdIndexRoute,
}

const CoreUsersUserIdRouteRouteWithChildren =
  CoreUsersUserIdRouteRoute._addFileChildren(CoreUsersUserIdRouteRouteChildren)

interface CoreRouteRouteChildren {
  CoreIndexRoute: typeof CoreIndexRoute
  CoreUsersUserIdRouteRoute: typeof CoreUsersUserIdRouteRouteWithChildren
  CoreAudit_logsAuditLogIdRoute: typeof CoreAudit_logsAuditLogIdRoute
  CoreUsersInviteRoute: typeof CoreUsersInviteRoute
  CoreUsersNewRoute: typeof CoreUsersNewRoute
  CoreAudit_logsIndexRoute: typeof CoreAudit_logsIndexRoute
  CoreUsersIndexRoute: typeof CoreUsersIndexRoute
}

const CoreRouteRouteChildren: CoreRouteRouteChildren = {
  CoreIndexRoute: CoreIndexRoute,
  CoreUsersUserIdRouteRoute: CoreUsersUserIdRouteRouteWithChildren,
  CoreAudit_logsAuditLogIdRoute: CoreAudit_logsAuditLogIdRoute,
  CoreUsersInviteRoute: CoreUsersInviteRoute,
  CoreUsersNewRoute: CoreUsersNewRoute,
  CoreAudit_logsIndexRoute: CoreAudit_logsIndexRoute,
  CoreUsersIndexRoute: CoreUsersIndexRoute,
}

const CoreRouteRouteWithChildren = CoreRouteRoute._addFileChildren(
  CoreRouteRouteChildren,
)

interface StorageBucketIdRouteRouteChildren {
  StorageBucketIdSplatRoute: typeof StorageBucketIdSplatRoute
  StorageBucketIdIndexRoute: typeof StorageBucketIdIndexRoute
}

const StorageBucketIdRouteRouteChildren: StorageBucketIdRouteRouteChildren = {
  StorageBucketIdSplatRoute: StorageBucketIdSplatRoute,
  StorageBucketIdIndexRoute: StorageBucketIdIndexRoute,
}

const StorageBucketIdRouteRouteWithChildren =
  StorageBucketIdRouteRoute._addFileChildren(StorageBucketIdRouteRouteChildren)

interface StorageRouteRouteChildren {
  StorageBucketIdRouteRoute: typeof StorageBucketIdRouteRouteWithChildren
  StorageIndexRoute: typeof StorageIndexRoute
}

const StorageRouteRouteChildren: StorageRouteRouteChildren = {
  StorageBucketIdRouteRoute: StorageBucketIdRouteRouteWithChildren,
  StorageIndexRoute: StorageIndexRoute,
}

const StorageRouteRouteWithChildren = StorageRouteRoute._addFileChildren(
  StorageRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchemaRouteRoute: SchemaRouteRouteWithChildren,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AiRouteRoute: AiRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CoreRouteRoute: CoreRouteRouteWithChildren,
  StorageRouteRoute: StorageRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
