-- Custom types
begin;

create type supasheet.app_permission as enum(
  'supasheet.users:select',
  'supasheet.users:select_all',
  'supasheet.users:update',
  'supasheet.users:insert',
  'supasheet.users:delete',
  'supasheet.users:invite',
  'supasheet.users:ban',
  'supasheet.users:generate_link',
  'supasheet.user_roles:select',
  'supasheet.user_roles:select_all',
  'supasheet.user_roles:insert',
  'supasheet.user_roles:delete',
  'supasheet.role_permissions:select',
  'supasheet.role_permissions:select_all',
  'supasheet.role_permissions:insert',
  'supasheet.role_permissions:delete'
);

create type supasheet.app_role as enum('x-admin', 'admin', 'user');

commit;

-- USER ROLES
create table supasheet.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references supasheet.users on delete cascade not null,
  role supasheet.app_role not null,
  unique (user_id, role)
);

comment on table supasheet.user_roles is '{
  "label": "User Roles",
  "icon": "UserCheckIcon"
}';

alter table supasheet.user_roles enable row level security;

revoke all on table supasheet.user_roles
from
  authenticated,
  service_role;

grant
select
,
  insert,
update,
delete on table supasheet.user_roles to authenticated,
service_role;

-- ROLE PERMISSIONS
create table supasheet.role_permissions (
  id bigint generated by default as identity primary key,
  role supasheet.app_role not null,
  permission supasheet.app_permission not null,
  unique (role, permission)
);

comment on table supasheet.role_permissions is '{
  "label": "Role Permissions",
  "icon": "ShieldCheckIcon"
}';

alter table supasheet.role_permissions enable row level security;

revoke all on table supasheet.role_permissions
from
  authenticated,
  service_role;

grant
select
,
  insert,
update,
delete on table supasheet.role_permissions to authenticated,
service_role;

-- Performance indexes
create index idx_user_roles_user_id on supasheet.user_roles (user_id);

create index idx_user_roles_role on supasheet.user_roles (role);

create index idx_role_permissions_role on supasheet.role_permissions (role);

create index idx_role_permissions_permission on supasheet.role_permissions (permission);

create index idx_role_permissions_role_permission on supasheet.role_permissions (role, permission);

create or replace function supasheet.has_permission (requested_permission supasheet.app_permission) returns boolean as $$
declare
  _user_id uuid;
begin
  _user_id := (select auth.uid()); -- evaluated once
  return exists (
    select 1
    from supasheet.role_permissions rp
    inner join supasheet.user_roles ur on rp.role = ur.role
    where ur.user_id = _user_id
      and rp.permission = requested_permission
  );
end;
$$ language plpgsql stable security definer
set
  search_path = '';

grant
execute on function supasheet.has_permission (supasheet.app_permission) to authenticated,
service_role;

create or replace function supasheet.has_role (requested_role supasheet.app_role) returns boolean as $$
declare
  _user_id uuid;
begin
  _user_id := (select auth.uid());
  return exists (
    select 1 from supasheet.user_roles
    where user_id = _user_id and role = requested_role
  );
end;
$$ language plpgsql stable security definer
set
  search_path = '';

create index on supasheet.user_roles using btree (user_id);

grant
execute on function supasheet.has_role (supasheet.app_role) to authenticated,
service_role;

create policy "User can view their own role" on supasheet.user_roles for
select
  to authenticated using (
    (
      select
        auth.uid ()
    ) = user_id
    and supasheet.has_permission ('supasheet.user_roles:select')
  );

create policy "User can view all user roles" on supasheet.user_roles for
select
  to authenticated using (
    supasheet.has_permission ('supasheet.user_roles:select_all')
  );

create policy "User can insert user roles" on supasheet.user_roles for insert to authenticated
with
  check (
    supasheet.has_permission ('supasheet.user_roles:insert')
  );

create policy "User can delete user roles" on supasheet.user_roles for delete to authenticated using (
  supasheet.has_permission ('supasheet.user_roles:delete')
);

create policy "User can view their own role permissions" on supasheet.role_permissions for
select
  to authenticated using (
    (
      select
        (supasheet.has_role (role))
    )
    and supasheet.has_permission ('supasheet.role_permissions:select')
  );

create policy "User can view all role permissions" on supasheet.role_permissions for
select
  to authenticated using (
    supasheet.has_permission ('supasheet.role_permissions:select_all')
  );

create policy "User can insert role permissions" on supasheet.role_permissions for insert to authenticated
with
  check (
    supasheet.has_permission ('supasheet.role_permissions:insert')
  );

create policy "User can delete role permissions" on supasheet.role_permissions for delete to authenticated using (
  supasheet.has_permission ('supasheet.role_permissions:delete')
);

create policy "User can view all users" on supasheet.users for
select
  to authenticated using (
    supasheet.has_permission ('supasheet.users:select_all')
  );

create policy "User can insert users" on supasheet.users for insert to authenticated
with
  check (
    supasheet.has_permission ('supasheet.users:insert')
  );

create policy "User can update users" on supasheet.users
for update
  to authenticated using (
    supasheet.has_permission ('supasheet.users:update')
  );

create policy "User can delete users" on supasheet.users for delete to authenticated using (
  supasheet.has_permission ('supasheet.users:delete')
);

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.users:select');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.users:insert');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.users:update');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.users:delete');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.users:invite');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.users:ban');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.users:generate_link');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.user_roles:select');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.user_roles:insert');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.user_roles:delete');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.role_permissions:select');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.role_permissions:insert');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.role_permissions:delete');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.users:select_all');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.user_roles:select_all');

insert into
  supasheet.role_permissions (role, permission)
values
  ('x-admin', 'supasheet.role_permissions:select_all');

insert into
  supasheet.role_permissions (role, permission)
values
  ('user', 'supasheet.users:select');

insert into
  supasheet.role_permissions (role, permission)
values
  ('user', 'supasheet.user_roles:select');

insert into
  supasheet.role_permissions (role, permission)
values
  ('user', 'supasheet.role_permissions:select');

-- create or replace function supasheet.new_user_created_setup()
-- returns trigger 
-- language plpgsql 
-- as $$
-- begin
--   insert into supasheet.user_roles (user_id, role) values (new.id, 'user');
--   return new;
-- end;
-- $$;
-- -- trigger the function every time a user is created
-- create trigger on_user_created
--     after insert
--     on supasheet.users
--     for each row
-- execute procedure supasheet.new_user_created_setup();
